name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Specify the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements.txt file

      - name: Start Flask app
        run: |
          python app.py &  # Start the Flask app in the background
          sleep 5  # Wait for the app to start

          # Install and set up ngrok
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip

          # Set ngrok auth token
          ./ngrok  authtoken 2P1VicjMbdrg4uhgYzrZgIPh5IR_6oHHzgDzbWTnhDi6s6fq3

          # Expose the Flask app's port using ngrok
          ./ngrok http 5000  # Replace 5000 with the port your Flask app is running on
